<?php 
/*
Template Name: Privacy Policy
*/
get_header();

get_sidebar('left');
?>

	<div class="col-md-6 col-sm-6 col-12">
		<div class="main-content about-us mt-4 terms">
		<span class="mb-4">Privacy Policy</span>
                
                
               <p><br> XR Sports Group, LLC. (“XR Sports”, “we” or “us”) develops, operates and maintains software that both helps brands create, deliver and manage online and offline gaming & esports competitions.
We are committed to respecting the privacy rights of our customers, visitors and other users of xrsports.gg and related websites, applications, services and mobile applications provided by us and on/in which this privacy policy is posted or referenced (collectively, the “Services”). We created this privacy policy to give you confidence as you use the Services and to demonstrate our commitment to the protection of privacy.<br>
BY VISITING OUR WEBSITES OR OTHERWISE USING OR ACCESSING THE SERVICES, YOU CONSENT TO OUR COLLECTION, USE, STORAGE, DELETION, TRANSFER TO THE UNITED STATES (IF APPLICABLE) AND DISCLOSURE OF PERSONAL DATA RELATING TO YOU AS SET FORTH IN THIS PRIVACY POLICY, WHICH IS INCORPORATED BY REFERENCE INTO OUR TERMS OF SERVICES.<br>
<strong>Personal Data we Collect</strong> <br>
When you interact with us through the Services, we may collect “personally identifiable information” or ”Personal Data” (i.e. any information relating to an identified or identifiable natural person) and other information from you, including as described below. The legal bases for our processing of Personal Data are primarily that the processing is necessary for providing the Services and that the processing is carried out in our legitimate interests, which are further explained in the “How We Use Information” Section. We may also process Personal Data upon your consent, asking for it as appropriate.
Registration: When you register for access to the Services, as a tournament organizer, event attendee, general user or otherwise, the Personal Data we may collect includes, without limitation, your name, address, email address, zip code and other information..
Purchases: If you make a purchase, such as customized avatars and other additional services for your account or registering for a paid event, we will collect financial information from you (e.g., your credit card number and expiration date, billing address, account information for online payment providers like PayPal, etc.), some of which may constitute Personal Data. If you use our payment processing services, for example, to offer or receive prize money, we will collect financial information from you (e.g., your bank account information, an address to send checks, account information for online payment providers like Paypal, etc.) as necessary to facilitate payments and information required for tax purposes (e.g., your taxpayer identification number).
Registration for Tournaments and Other Events.: Event registration pages set up by tournament organizers can request various additional information from event attendees in connection with registration for a tournament or event through the Services, some of which may be Personal Data. Any information provided in connection with registration for, and access to, a tournament or event will be available to us and will be held by us in accordance with this Privacy Policy. Such information may be delivered to the tournament organizer.
Contacting Us: If you contact us by, for example, making an inquiry, responding to one of our surveys or using certain parts of the Services, we may collect any information you provide, including Personal Data.
<strong>Non-Personal Information We Collect</strong><br>
When you interact with the Services, we may collect certain personally non-identifiable information and aggregate information on our users’ demographics, interests and behavior based on your Personal Data and other information and aggregate such information so that it does not identify you personally. We consider such aggregated information as Non-Personal Data. This information is collected passively using various technologies and cannot, in and of itself, be used to identify you specifically. We also collect Non-Personal Data (including, without limitation, of the type described above) from third parties. The information we collect from third parties may be combined with the information we collect.
How We Use Information.<br>
We take steps designed to ensure that only those employees who need access to your Personal Data to fulfil their employment duties will have access to it. We use your information, including Personal Data, to provide you with access to or use of the Services or functionality, to monitor your use of such Services or functionality, to respond to your inquiries or to process payments for your purchases. Your information, including Personal Data, may be used by us for other purposes, as well. For example, we may use your information, including Personal Data, for internal business purposes, including, without limitation, to help us improve the content and functionality of the Services, to understand our users better, to improve the Services, to protect against, identify or address wrongdoing, to enforce our Terms of Services, to manage your account and provide you with customer service, and generally to manage the Services and our business. Your information, including Personal Data, may also be used to contact you for our marketing and advertising purposes, including, without limitation, to inform you about services or events we believe might be of interest to you, to develop promotional or marketing materials and provide those materials to you, and to display content and advertising on or off the Services. We also permit tournament organizers to email users and event attendees that are registered or have registered in the past for their tournaments.
Sharing Information<br>
We may share your information, including Personal Data, with non-affiliated and affiliated third parties. When we share your Personal Data to third parties, we take reasonable measures to ensure that the rules set forth in this Privacy Policy are complied with and these third parties provide sufficient guarantees to implement appropriate technical and organizational measures.
In the event of a corporate sale, merger, reorganization, dissolution or similar event, Personal Data may be part of the transferred assets. You acknowledge and agree that any successor to or acquirer of XR Sports Group, LLC. or its assets will continue to have the right to use your Personal Data and other information in accordance with the terms of this Privacy Policy.
We may also share your Personal Data with our subsidiaries and/or affiliates for purposes consistent with this Privacy Policy. Our subsidiaries and affiliates will be bound to maintain that Personal Data in accordance with this Privacy Policy.
Personal Data provided on event registration pages will be disclosed to the tournament organizer. Note that the tournament organizers are not bound to treat your Personal Data in accordance with this Privacy Policy. You agree that we are not responsible for the actions of these tournament organizers with respect to your Personal Data. It is important that you review the applicable policies of the tournament organizers before providing Personal Data or other information.
You can connect your XR Sports account to your accounts on social media, streaming and other third party services, in which case we may collect, use, disclose, transfer and store information relating to your account with such third party services in accordance with this Privacy Policy. For example, if you connect with Facebook, we store your Facebook ID, first name, last name, email, location, friends list and profile picture and use them to connect with your Facebook account to provide certain functionality on the Services, such as recommending events that your Facebook friends are interested in and sharing the events you are interested in with certain groups of people like your Facebook friends.
We may disclose your Personal Data if required to do so by law (including, without limitation, responding to a subpoena or request from law enforcement, court or government agency) or in the good faith belief that such action is necessary or appropriate (i) to comply with a legal obligation, (ii) to protect or defend our rights, interests or property or that of third parties, (iii) to prevent, investigate or identify possible wrongdoing in connection with the Services, (iv) to act in urgent circumstances to protect the personal safety of users of the Services or the public or (v) to protect against legal liability.
Children<br>
If you live in a country in the EU/EEA, you must be at least 16 years old to use our Services or such greater age required in your country to register for or use our Services. If you live in any other country except those in the EU/EEA, you must be at least 13 years old to use our Services or such greater age required in your country to register for or use our Services. In addition to being of the minimum required age to use our Services under applicable law, if you are not old enough to have authority to agree to our Policy in your country, your parent or guardian must agree to our Privacy Policy on your behalf. If you have any concerns about your child’s Personal Data, please contact us at hello@xrsports.gg
Our use of Cookies and Similar Technologies<br>
We may collect your information, including Personal Data, through the use of cookies, pixel tags, local shared objects, web storage and other similar technologies. By using the Services, you are consenting to the use of the technologies described herein and similar technologies to collect and store information on your device or web browser.
A cookie is a piece of information placed on your computer or mobile device through your web browser when you access and/or use the Services that stores text and which can later be read back by the Services or third parties. Cookies are used to recognize your browser and you as a unique user. Cookies may be session cookies (i.e., last only for one browser session) or persistent cookies (i.e., continue on your browser until they are affirmatively deleted). You can manage cookies through your web browser's option settings, and through those settings you may be able (i) to receive notifications when you are receiving new cookies, (ii) to disable cookies or (iii) to delete cookies. Please refer to your web browser's help section for information on how to do this.
A pixel tag, or web beacon, is a tiny invisible tag or graphic placed on certain parts of the Services or other websites, in emails or in certain other downloadable content, but not on your computer, mobile device or browser, except to the extent that you download the content that contains such tags. Pixel tags do not store information on your computer, mobile device or browser (although they are occasionally downloaded to your computer if contained in an email or other downloadable content) so they cannot be managed by you except by deleting the content in which the tag is contained.
A local shared object is similar to a cookie, except it can store more than just text. Local shared objects are stored on your computer or mobile device. You can manage privacy and storage settings for local shared objects by visiting Flash’s Website Storage Settings panel. We may use third-party website analytics services in connection with the Services, including, for example, to register mouse clicks, mouse movements, scrolling activity and text typed into our websites. We use the information collected from these services to help make the Services easier to use and as otherwise set forth in this Privacy Policy. These website analytics services generally do not collect Personal Data unless you voluntarily provide it and generally do not track your browsing habits across websites that do not use their services.
To determine if users have interacted with content across multiple devices and to match such devices, we may work with partners who analyze device activity data and/or rely on your information (including demographic, geographic and interest-based data). To supplement this analysis, we may also provide de-identified data to these partners. Based on this data, we may then display targeted advertisements across devices that we believe are associated or use this data to further analyze usage of Services across devices.
We use and allow third parties to use these technologies for a variety of purposes, including, without limitation, the operation of the Services or parts of the Services, monitoring the Services and to analyzing how you use the Services, allowing us to provide certain functionality on the Services and to remember your preferences, delivering advertisements to you, both on and off the Services. By using these technologies, we aim to provide advertisements targeted to your interests. Sometimes this is called online behavioral, interest-based, or retargeted advertising. For more information on these types of ads, or to stop use of tracking technologies for these purposes, go to www.aboutads.info or www.networkadvertising.org.
Your choices<br>
You can use the Services without providing any Personal Data or with limiting the Personal Data you provide. If you choose not to provide any Personal Data or limit the Personal Data you provide, you may not be able to use certain functionality of the Services. For instance, in order to register for an event, your name and email address will be required.
Opt out: You can "opt out" of receiving our marketing emails from us by clicking unsubscribe within the email. It may take several days for us to process an unsubscribe request. You can stop receiving Service communications and tournament organizers’ emails only by contacting us at hello@xrsports.gg. Further, tournament organizers who have received your Personal Data in accordance with this Privacy Policy may still use that Personal Data to contact you in accordance with their own policies, but they may not use our system to do so. You can also close your XR Sports account. Once your account is closed, you will permanently lose all of your profile information.
Do Not Track<br>
We currently do not participate in any "Do Not Track" frameworks that would allow us to respond to signals or other mechanisms from you regarding the collection of your Personal Data.
Special Information for California Residents<br>
California “Shine the Light” Request.: California residents may request a list of all third parties to which we have disclosed certain personally identifiable information about you for marketing purposes. You may make one request per calendar year. In your request, please attest to the fact that you are a California resident and provide a current California address for your response. You may request this information in writing by contacting us at:
Attn: XR Sports Privacy<br>
XR Sports Group, LLC<br>
5757 Main St.<br>
Suite 200<br>
Frisco, TX 75034<br>
hello@xrsports.gg<br>
Exclusions<br>
This Privacy Policy does not apply to any Personal Data collected by us other than Personal Data collected through the Services. This Privacy Policy does not apply to any unsolicited information you provide to us or another user or visitor through the Services or through any other means. This includes, but is not limited to, information posted to any public areas of the Services, such as bulletin boards, any ideas for new products or modifications to existing products, claim or demand letters, Digital Millennium Copyright Act notices and other unsolicited submissions, all of which will be deemed to be non-confidential and will be used, reproduced, disclosed, distributed and exploited by us without limitation or attribution.
Links to Other Web Sites<br>
This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by us. The policies and procedures we described here do not apply to those sites, nor do we endorse or review those sites. We suggest contacting those sites directly for information on their policies.
Exclusions<br>
The security of your Personal Details are important to us. We endeavor to follow generally accepted industry standards to protect the Personal Data submitted to us, both during transmission and in storage. For example, when you enter sensitive information on our Site, we encrypt that information using Secure Socket Layer (SSL) technology.
We store and process your information on our servers in the United States and abroad. We maintain industry standard backup and archival systems. By using the Services, you consent to the transfer of information to countries outside your country of residence, including the United States, which may have different data protection rules than in your country. While such information is outside of your country residence, it is subject to the laws of the country in which it is held, and may be subject to disclosure to the governments, courts or law enforcement or regulatory agencies of such other country, pursuant to the laws of such country. However, our practices regarding your Personal Data will at all times continue to be governed by this Privacy Policy and, if applicable, we will comply with the General Data Protection Regulation (“GDPR”) requirements providing adequate protection for the transfer of Personal Data from the EU/EEA to third country.
Although we make good faith efforts to store Personal Data in a secure operating environment that is not open to the public, we do not and cannot guarantee the security of your Personal Data. In particular, no Internet or e-mail transmission is ever fully secure or error free. In particular, e-mail sent to or from the Services may not be secure. Therefore, you should take special care in deciding what information you send to us via e-mail and what Personal Data you disclose on the Internet.
If at any time during or after our relationship we believe that the security of your Personal Data may have been compromised, subject to applicable laws (including the GDPR), we may seek to notify you of that development. If a notification is legally required, we will endeavor to notify you as promptly as possible under the circumstances. If we have your e-mail address, we may notify you by e-mail to the most recent e-mail address you have provided us in your account profile. To receive these notices, you must check your e-mail account using your computer or mobile device and email application software. You consent to our use of e-mail as a means of such notification. If you prefer for us to use the mail to notify you in this situation, please e-mail us at hello@xrsports.gg. Please include your address when you submit your request. You can make this election any time, and it will apply to notifications we make after a reasonable time thereafter for us to process your request. You may also use this e-mail address to request a print copy, at no charge, of an electronic notice we have sent to you regarding a compromise of your Personal Data.
Changes to This Privacy Policy.<br>
We may update or modify our Privacy Policy from time to time. Modifications to this Privacy Policy will be posted to our battlefy.com website. In certain circumstances, we may choose to provide you with additional notice of such modifications by email, in-Service notifications or otherwise. Please review this policy periodically, and especially before you provide any Personal Data. YOUR CONTINUED USE OF THE SERVICES FOLLOWING THE EFFECTIVENESS OF ANY MODIFICATIONS TO THIS PRIVACY POLICY CONSTITUTES ACCEPTANCE OF THOSE MODIFICATIONS. IF ANY MODIFICATION TO THIS PRIVACY POLICY IS NOT ACCEPTABLE TO YOU, YOUR SOLE REMEDY IS TO CEASE ACCESSING, BROWSING AND OTHERWISE USING THE SERVICES.
Your Rights:<br>
You may access and update your Personal Data by logging into your account and visiting your account management page. You may also contact us directly at hello@xrsports.gg with respect to Personal Data that is not accessible through the Services. We will take reasonable steps to respond to requests relating to Personal Data within 30 days. However, subject to applicable laws, we may reject requests that we find to be unreasonable (i.e., require disproportionate efforts or material changes to our information systems), impractical or abusive (e.g., repetitive requests, requests made in bad faith or requests that would compromise third party information). Note that you may not have access to or the ability to update Non-Personal Data, much of which is held in aggregate form. Under the GDPR, you may be entitled to additional rights, including: (i) the right to withdraw consent to processing where consent is the basis of processing; (ii) the right to access your Personal Data and certain other supplementary information, under certain conditions; (iii) the right to object to unlawful data processing, under certain conditions; (iv) the right to erasure of Personal Data about you, under certain conditions; (v) the right to demand that we restrict processing of your Personal Data, under certain conditions, if you believe we have exceeded the legitimate basis for processing, processing is no longer necessary, are processing, or believe your Personal Data is inaccurate; (vi) the right to data portability of Personal Data concerning you that you provided us in a structured, commonly used, and machine-readable format, under certain conditions; (vii) the right object to decisions being taken by automated means which produce legal effects concerning you or similarly significantly affect you, under certain conditions; (viii) the right to lodge a complaint with data protection authorities. If you want to learn more about your rights under the GDPR, you can visit the European Commission’s page on Data Protection at:
http://ec.europa.eu/justice/data-protection/index_en.htm<br>
Retention and Deletion.<br>
We may retain your Personal Data as long as they are needed, or as required by applicable laws, regulations, or government orders. You may close your account by contacting us.<br>
Contact XR Sports<br>
If you have any questions or comments about this Privacy Policy or your Personal Data, to make an access or correction request, to exercise any applicable rights, to make a complaint, or to obtain information about our policies and practices with respect to any service providers outside your country of residence, our Privacy Officer (or Data Protection Officer) can be reached by mail or email using the following contact information:
Attn: XR Sports Privacy<br>
XR Sports Group, LLC<br>
5757 Main St.<br>
Suite 200<br>
Frisco, TX 75034<br>
hello@xrsports.gg<br>

                
                
			
    		<div class="abt-logo text-center mt-4">
    			<img class="img-fluid mt-4" src="<?php echo get_bloginfo('url') ?>/wp-content/themes/pixiefreak-child/image/xr-logo1.png">
    		</div>
        </div>
	</div>

<?php 
get_sidebar('right');
get_footer();
?>

